apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

commonLabels:
  app.kubernetes.io/component: webhook-server

images:
- name: webhook-server
  newName: quay.io/edge-infrastructure/kernel-module-management-webhook-server
  newTag: latest
