commit_markup: Upstream-Commit

downstream:
  create_draft_prs: true
  github_repo_name: rh-ecosystem-edge/kernel-module-management
  local_repo_path: _gitstream_downstream
  max_open_items: 3
  ignore_authors:
    - "dependabot[bot]"

log_level: 1000

diff:
  commits_since: 2022-08-31T00:00:00.00Z

sync:
  before_commit:
    - [go, mod, tidy]
    - [go, mod, vendor]

upstream:
  ref: main
  url: https://github.com/kubernetes-sigs/kernel-module-management

