FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11 as builder

WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum
COPY cmd cmd
COPY api api
COPY internal internal
COPY Makefile Makefile
COPY vendor vendor

# Build
RUN make signimage

RUN dnf install -y kernel-devel

FROM registry.redhat.io/ubi8/ubi-micro:8.7

COPY --from=builder /workspace/signimage /usr/src/kernels/*/scripts/sign-file /usr/local/bin
USER 65534:65534

ENTRYPOINT ["/usr/local/bin/signimage"]
