FROM registry.access.redhat.com/ubi9/ubi-minimal:9.2 as ksource

# install the package that will contain the sign utilities
RUN ["microdnf", "install", "-y", "kernel-devel"]

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.2

COPY --from=ksource /usr/src/kernels/*/scripts/sign-file /usr/local/bin/
USER 65534:65534

ENTRYPOINT ["/usr/local/bin/sign-file"]
