apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

patches:
- path: ocp.patch.yaml

images:
- name: must-gather
  newName: quay.io/edge-infrastructure/kernel-module-management-must-gather
  newTag: release-2.5
- name: signer
  newName: quay.io/edge-infrastructure/kernel-module-management-signimage
  newTag: release-2.5

configurations:
- kustomizeconfig.yaml
