apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- configmap-cluster-ca.yaml
- configmap-service-ca.yaml

patchesStrategicMerge:
- manager_auth_proxy_patch.yaml
- manager_config_patch.yaml
- ocp.patch.yaml

images:
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: registry.redhat.io/openshift4/ose-kube-rbac-proxy
  newTag: v4.12
- name: must-gather
  newName: quay.io/edge-infrastructure/kernel-module-management-must-gather
  newTag: latest
- name: signer
  newName: quay.io/edge-infrastructure/kernel-module-management-signimage
  newTag: latest

configurations:
- kustomizeconfig.yaml
