#!/usr/bin/env bash

OUTPUT_DIR="${OUTPUT_DIR:-must-gather/$(date +%Y%m%d_%H%M%S)}"
readonly OUTPUT_DIR

HUB=false
NS=openshift-operators

readonly COMMON_KINDS='clusterrolebindings,configmaps,events,pods,roles,rolebindings,serviceaccounts'
readonly BUILD_KINDS="${COMMON_KINDS},builds,jobs.batch"

collect_common() {
  echo "Collecting common objects"

  oc adm inspect clusterversions.config.openshift.io/version --dest-dir="$OUTPUT_DIR/inspect"
  oc adm inspect crd,images --dest-dir="$OUTPUT_DIR/inspect"

  oc adm inspect \
    -n "$NS" \
    "${COMMON_KINDS},deployment.apps,services" \
    --dest-dir="$OUTPUT_DIR/inspect"

  oc adm inspect imagestreams -n openshift driver-toolkit --dest-dir="$OUTPUT_DIR/inspect"
}

collect() {
  echo "Collecting KMM objects and logs"

  oc adm inspect modules,preflightvalidations,preflightvalidationsocp -A --dest-dir="$OUTPUT_DIR/inspect"
  oc adm inspect clusterclaims --dest-dir="$OUTPUT_DIR/inspect"

  oc -n "$NS" logs "deployment/kmm-operator-controller-manager" > "${OUTPUT_DIR}/kmm-operator-controller-manager.log"

  namespaces=$(oc get daemonset -A -l kmm.node.kubernetes.io/module.name --no-headers -o custom-columns="NS:.metadata.namespace")
  IFS=" " read -r -a namespaces <<< "$(echo "${namespaces[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')"
  for ns in "${namespaces[@]}"; do
    echo "Collecting data in namespace ${ns}"

    oc adm inspect -n "$ns" "daemonset.apps,${BUILD_KINDS}" --dest-dir="$OUTPUT_DIR/inspect"
  done
}

collect_hub() {
  echo "Collecting KMM-Hub objects and logs"

  oc adm inspect managedclustermodules,managedclusters --dest-dir="$OUTPUT_DIR/inspect"
  oc adm inspect manifestworks -A --dest-dir="$OUTPUT_DIR/inspect"
  oc adm inspect "${BUILD_KINDS}" -A --dest-dir="$OUTPUT_DIR/inspect"

  oc -n "$NS" logs "deployment.apps/kmm-operator-hub-controller-manager" > "${OUTPUT_DIR}/kmm-operator-hub-controller-manager.log"
}

while getopts "hn:u" arg; do
  case $arg in
    n)
      NS="${OPTARG}"
      ;;
    u)
      HUB=true
      ;;
    h | *) # Display help.
      echo 'Usage: gather [ -n NAMESPACE ] [ -u ]'
      exit 0
      ;;
  esac
done

mkdir -p "$OUTPUT_DIR"

collect_common

if [ $HUB == true ]; then
  collect_hub
else
  collect
fi
