#!/usr/bin/env bash

OUTPUT_DIR="${OUTPUT_DIR:-must-gather/$(date +%Y%m%d_%H%M%S)}"
readonly OUTPUT_DIR

HUB=false
NS=''

readonly COMMON_KINDS='clusterrolebindings,configmaps,events,pods,roles,rolebindings,serviceaccounts'
readonly BUILD_KINDS="${COMMON_KINDS},builds"

collect_common() {
  echo "Collecting common objects"

  oc adm inspect clusterversions.config.openshift.io/version --dest-dir="$OUTPUT_DIR/inspect"
  oc adm inspect crd,images,nodes --dest-dir="$OUTPUT_DIR/inspect"

  oc adm inspect \
    -n "$NS" \
    "${COMMON_KINDS},deployment.apps,services" \
    --dest-dir="$OUTPUT_DIR/inspect"

  oc adm inspect imagestreams -n openshift driver-toolkit --dest-dir="$OUTPUT_DIR/inspect"
}

collect() {
  echo "Collecting KMM objects and logs"

  oc adm inspect modules,nodemodulesconfigs,preflightvalidations,preflightvalidationsocp -A --dest-dir="$OUTPUT_DIR/inspect"
  oc adm inspect clusterclaims --dest-dir="$OUTPUT_DIR/inspect"

  oc -n "$NS" logs "deployment/kmm-operator-controller-manager" > "${OUTPUT_DIR}/kmm-operator-controller-manager.log"

  for ns in $(oc get modules -A --no-headers -o custom-columns="NS:.metadata.namespace"); do
    echo "Collecting data in namespace ${ns}"

    oc adm inspect -n "$ns" "daemonset.apps,${BUILD_KINDS}" --dest-dir="$OUTPUT_DIR/inspect"
  done
}

collect_hub() {
  echo "Collecting KMM-Hub objects and logs"

  oc adm inspect managedclustermodules,managedclusters --dest-dir="$OUTPUT_DIR/inspect"
  oc adm inspect manifestworks -A --dest-dir="$OUTPUT_DIR/inspect"
  oc adm inspect "${BUILD_KINDS}" -n "${NS}" --dest-dir="$OUTPUT_DIR/inspect"

  oc -n "$NS" logs "deployment.apps/kmm-operator-hub-controller-manager" > "${OUTPUT_DIR}/kmm-operator-hub-controller-manager.log"
}

while getopts "hn:u" arg; do
  case $arg in
    n)
      NS="${OPTARG}"
      ;;
    u)
      HUB=true

      if [ -z "${NS}" ]; then
        NS='openshift-kmm-hub'
      fi
      ;;
    h | *) # Display help.
      echo 'Usage: gather [ -n NAMESPACE ] [ -u ]'
      exit 0
      ;;
  esac
done

if [ -z "${NS}" ]; then
  NS='openshift-kmm'
fi

mkdir -p "$OUTPUT_DIR"

collect_common

if [ $HUB == true ]; then
  collect_hub
else
  collect
fi
