// Code generated by MockGen. DO NOT EDIT.
// Source: initramfsmodule_reconciler.go
//
// Generated by this command:
//
//	mockgen -source=initramfsmodule_reconciler.go -package=controllers -destination=mock_initramfsmodule_reconciler.go initramfsModuleReconcilerHelper
//
// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/rh-ecosystem-edge/kernel-module-management/api/v1beta1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockinitramfsModuleReconcilerHelper is a mock of initramfsModuleReconcilerHelper interface.
type MockinitramfsModuleReconcilerHelper struct {
	ctrl     *gomock.Controller
	recorder *MockinitramfsModuleReconcilerHelperMockRecorder
}

// MockinitramfsModuleReconcilerHelperMockRecorder is the mock recorder for MockinitramfsModuleReconcilerHelper.
type MockinitramfsModuleReconcilerHelperMockRecorder struct {
	mock *MockinitramfsModuleReconcilerHelper
}

// NewMockinitramfsModuleReconcilerHelper creates a new mock instance.
func NewMockinitramfsModuleReconcilerHelper(ctrl *gomock.Controller) *MockinitramfsModuleReconcilerHelper {
	mock := &MockinitramfsModuleReconcilerHelper{ctrl: ctrl}
	mock.recorder = &MockinitramfsModuleReconcilerHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinitramfsModuleReconcilerHelper) EXPECT() *MockinitramfsModuleReconcilerHelperMockRecorder {
	return m.recorder
}

// finalize mocks base method.
func (m *MockinitramfsModuleReconcilerHelper) finalize(ctx context.Context, irm *v1beta1.InitramfsModule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "finalize", ctx, irm)
	ret0, _ := ret[0].(error)
	return ret0
}

// finalize indicates an expected call of finalize.
func (mr *MockinitramfsModuleReconcilerHelperMockRecorder) finalize(ctx, irm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "finalize", reflect.TypeOf((*MockinitramfsModuleReconcilerHelper)(nil).finalize), ctx, irm)
}

// handleMIC mocks base method.
func (m *MockinitramfsModuleReconcilerHelper) handleMIC(ctx context.Context, irm *v1beta1.InitramfsModule, nodes []v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleMIC", ctx, irm, nodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleMIC indicates an expected call of handleMIC.
func (mr *MockinitramfsModuleReconcilerHelperMockRecorder) handleMIC(ctx, irm, nodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleMIC", reflect.TypeOf((*MockinitramfsModuleReconcilerHelper)(nil).handleMIC), ctx, irm, nodes)
}

// handleMachineConfig mocks base method.
func (m *MockinitramfsModuleReconcilerHelper) handleMachineConfig(ctx context.Context, irm *v1beta1.InitramfsModule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleMachineConfig", ctx, irm)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleMachineConfig indicates an expected call of handleMachineConfig.
func (mr *MockinitramfsModuleReconcilerHelperMockRecorder) handleMachineConfig(ctx, irm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleMachineConfig", reflect.TypeOf((*MockinitramfsModuleReconcilerHelper)(nil).handleMachineConfig), ctx, irm)
}

// handleMachineConfigPool mocks base method.
func (m *MockinitramfsModuleReconcilerHelper) handleMachineConfigPool(ctx context.Context, irm *v1beta1.InitramfsModule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handleMachineConfigPool", ctx, irm)
	ret0, _ := ret[0].(error)
	return ret0
}

// handleMachineConfigPool indicates an expected call of handleMachineConfigPool.
func (mr *MockinitramfsModuleReconcilerHelperMockRecorder) handleMachineConfigPool(ctx, irm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handleMachineConfigPool", reflect.TypeOf((*MockinitramfsModuleReconcilerHelper)(nil).handleMachineConfigPool), ctx, irm)
}

// listSelectedNodes mocks base method.
func (m *MockinitramfsModuleReconcilerHelper) listSelectedNodes(ctx context.Context, irm *v1beta1.InitramfsModule) ([]v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "listSelectedNodes", ctx, irm)
	ret0, _ := ret[0].([]v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// listSelectedNodes indicates an expected call of listSelectedNodes.
func (mr *MockinitramfsModuleReconcilerHelperMockRecorder) listSelectedNodes(ctx, irm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "listSelectedNodes", reflect.TypeOf((*MockinitramfsModuleReconcilerHelper)(nil).listSelectedNodes), ctx, irm)
}
