apiVersion: v1
data:
  controller_manager_config.yaml: |
    healthProbeBindAddress: :8081
    metricsBindAddress: 127.0.0.1:8080
    webhookPort: 9443
    leaderElection:
      enabled: true
      resourceID: kmm-hub.sigs.x-k8s.io
kind: ConfigMap
metadata:
  name: kmm-operator-hub-manager-config
