#!/usr/bin/env bash

set -euxo pipefail

: "$BUNDLE_GEN_FLAGS"
: "${MANIFESTS_DIR:=config/manifests}"
: "$OPERATOR_SDK"
: "$PKG"
: "$SOURCE_DIR"
: "${SUFFIX:=}"
: "${INCLUDE_NETWORK_POLICIES:=false}"

readonly BUNDLE_DIR="bundle${SUFFIX}"

DIR=$(mktemp -d)
readonly DIR

cd "$DIR"

cp -r "$SOURCE_DIR/config" "$SOURCE_DIR/PROJECT" "$DIR"

oc kustomize "$MANIFESTS_DIR" | "$OPERATOR_SDK" generate bundle \
  --output-dir "$BUNDLE_DIR" \
  --package "$PKG" \
  $BUNDLE_GEN_FLAGS

# add network policies
if [ "$INCLUDE_NETWORK_POLICIES" = "true" ] && [ -d "$SOURCE_DIR/config/network-policy" ]; then
  for np_file in "$SOURCE_DIR/config/network-policy"/*.yaml; do
    if [ -f "$np_file" ] && [ "$(basename "$np_file")" != "kustomization.yaml" ]; then
      filename=$(basename "$np_file" .yaml)
      cp "$np_file" "$BUNDLE_DIR/manifests/kmm-operator${SUFFIX}-${filename}_networking.k8s.io_v1_networkpolicy.yaml"
    fi
  done
fi

mv "$BUNDLE_DIR" "$SOURCE_DIR/$BUNDLE_DIR"
mv bundle.Dockerfile "$SOURCE_DIR/bundle${SUFFIX}.Dockerfile"

rm -fr "$DIR"
