// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -package=networkpolicy -destination=mock_manager.go Manager
//
// Package networkpolicy is a generated GoMock package.
package networkpolicy

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// DeployNetworkPolicies mocks base method.
func (m *MockManager) DeployNetworkPolicies(ctx context.Context, namespace string, owner v1.Object, namePrefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployNetworkPolicies", ctx, namespace, owner, namePrefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeployNetworkPolicies indicates an expected call of DeployNetworkPolicies.
func (mr *MockManagerMockRecorder) DeployNetworkPolicies(ctx, namespace, owner, namePrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployNetworkPolicies", reflect.TypeOf((*MockManager)(nil).DeployNetworkPolicies), ctx, namespace, owner, namePrefix)
}
