// Code generated by MockGen. DO NOT EDIT.
// Source: maker.go
//
// Generated by this command:
//
//	mockgen -source=maker.go -package=ocpbuild -destination=mock_maker.go Maker
//
// Package ocpbuild is a generated GoMock package.
package ocpbuild

import (
	context "context"
	reflect "reflect"

	v1 "github.com/openshift/api/build/v1"
	api "github.com/rh-ecosystem-edge/kernel-module-management/internal/api"
	gomock "go.uber.org/mock/gomock"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Mockmaker is a mock of maker interface.
type Mockmaker struct {
	ctrl     *gomock.Controller
	recorder *MockmakerMockRecorder
}

// MockmakerMockRecorder is the mock recorder for Mockmaker.
type MockmakerMockRecorder struct {
	mock *Mockmaker
}

// NewMockmaker creates a new mock instance.
func NewMockmaker(ctrl *gomock.Controller) *Mockmaker {
	mock := &Mockmaker{ctrl: ctrl}
	mock.recorder = &MockmakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmaker) EXPECT() *MockmakerMockRecorder {
	return m.recorder
}

// makeBuildTemplate mocks base method.
func (m *Mockmaker) makeBuildTemplate(ctx context.Context, mld *api.ModuleLoaderData, pushImage bool, owner v10.Object) (*v1.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "makeBuildTemplate", ctx, mld, pushImage, owner)
	ret0, _ := ret[0].(*v1.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// makeBuildTemplate indicates an expected call of makeBuildTemplate.
func (mr *MockmakerMockRecorder) makeBuildTemplate(ctx, mld, pushImage, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "makeBuildTemplate", reflect.TypeOf((*Mockmaker)(nil).makeBuildTemplate), ctx, mld, pushImage, owner)
}
