#!/usr/bin/env bash

set -euxo pipefail

make generate bundle bundle-hub

if [[ $(git diff -I'^    createdAt: ') ]]; then
   echo 'Please run `make generate bundle bundle-hub` and repush'
   echo 'The following differences were found:'
   echo $(git diff -I'^    createdAt: ')
   exit 1
fi
