#!/usr/bin/env bash

set -euxo pipefail

make generate bundle bundle-hub

if [[ $(git diff) ]]; then
   echo 'Please run `make generate bundle bundle-hub` and repush'
   echo 'The following differences were found:'
   echo $(git diff)
   exit 1
fi
