#!/usr/bin/env bash

set -euxo pipefail

check_kmm_kmod () {
  # `|| true` is required in order to prevent `grep` from returning an error
  # code in case `kmm` wasn't found. Check `git blame` for additional info.
  oc debug node/$NODE -T -- chroot /host sh -c "lsmod | { grep kmm || true; }"
}
