#!/usr/bin/env bash

set -euxo pipefail

echo "Get first node..."
NODE=$(oc get nodes -o jsonpath='{.items..metadata.name}' | awk {'print $1'})

source check-kmm-kmod

echo "Label a node to match selector in Module afterwards..."
oc label node $NODE task=kmm-ci

echo "Deploy KMMO..."
make deploy

echo "Wait until the KMMO Deployment is Available..."
oc wait --for condition=Available --timeout 1m deployments.apps -n kmm-operator-system kmm-operator-controller-manager

echo "Check that the kmm_ci_a module is not loaded on the node..."
if check_kmm_kmod; then
   echo "Unexpected lsmod output - the module should not be loaded"
   exit 1
fi

echo " Add an kmm-ci Module that contains a valid mapping..."
oc apply -f ci/module-kmm-ci-variable.yaml

echo "Check that the module gets loaded on the node..."
timeout 1m bash -c 'until check_kmm_kmod; do sleep 3; done'

echo "Remove the Module..."
oc delete -f ci/module-kmm-ci-variable.yaml

echo "Check that the module gets unloaded from the node..."
timeout 1m bash -c 'until ! check_kmm_kmod; do sleep 3; done'
