- name: Individual tasks for each node
  block:
  - name: Install pre-requisites modules
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes
        - requests
        - jmespath

  - name: Migration loop through nodes 
    include_tasks: graceful_reboot.yaml
    loop: "{{ groups['workers'] }}"
    loop_control:
      loop_var: node

