// Code generated by MockGen. DO NOT EDIT.
// Source: syncronizedmap.go
//
// Generated by this command:
//
//	mockgen -source=syncronizedmap.go -package=syncronizedmap -destination=mock_syncronizedmap.go
//
// Package syncronizedmap is a generated GoMock package.
package syncronizedmap

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKernelOsDtkMapping is a mock of KernelOsDtkMapping interface.
type MockKernelOsDtkMapping struct {
	ctrl     *gomock.Controller
	recorder *MockKernelOsDtkMappingMockRecorder
}

// MockKernelOsDtkMappingMockRecorder is the mock recorder for MockKernelOsDtkMapping.
type MockKernelOsDtkMappingMockRecorder struct {
	mock *MockKernelOsDtkMapping
}

// NewMockKernelOsDtkMapping creates a new mock instance.
func NewMockKernelOsDtkMapping(ctrl *gomock.Controller) *MockKernelOsDtkMapping {
	mock := &MockKernelOsDtkMapping{ctrl: ctrl}
	mock.recorder = &MockKernelOsDtkMappingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKernelOsDtkMapping) EXPECT() *MockKernelOsDtkMappingMockRecorder {
	return m.recorder
}

// GetImage mocks base method.
func (m *MockKernelOsDtkMapping) GetImage(kernelVersion string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", kernelVersion)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockKernelOsDtkMappingMockRecorder) GetImage(kernelVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockKernelOsDtkMapping)(nil).GetImage), kernelVersion)
}

// SetImageStreamInfo mocks base method.
func (m *MockKernelOsDtkMapping) SetImageStreamInfo(osImage, dtkImage string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetImageStreamInfo", osImage, dtkImage)
}

// SetImageStreamInfo indicates an expected call of SetImageStreamInfo.
func (mr *MockKernelOsDtkMappingMockRecorder) SetImageStreamInfo(osImage, dtkImage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetImageStreamInfo", reflect.TypeOf((*MockKernelOsDtkMapping)(nil).SetImageStreamInfo), osImage, dtkImage)
}

// SetNodeInfo mocks base method.
func (m *MockKernelOsDtkMapping) SetNodeInfo(kernelVersion, osImage string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNodeInfo", kernelVersion, osImage)
}

// SetNodeInfo indicates an expected call of SetNodeInfo.
func (mr *MockKernelOsDtkMappingMockRecorder) SetNodeInfo(kernelVersion, osImage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNodeInfo", reflect.TypeOf((*MockKernelOsDtkMapping)(nil).SetNodeInfo), kernelVersion, osImage)
}
