---
apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm-ci-a
      kernelMappings:
        - literal: 4.18.0-372.19.1.el8_6.x86_64 
          containerImage: image-registry.openshift-image-registry.svc:5000/default/kmm-kmod:4.18.0f
          pull:
            insecureSkipTLSVerify: true
          build:
            pull:
              insecureSkipTLSVerify: true
            push:
              insecureSkipTLSVerify: true

            dockerfile: |
              FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:82faeb6a8caa174d9df3d259945ca161311fe6231d628e34ee0f1c8528371229 AS builder
              ARG KERNEL_VERSION
              WORKDIR /build
              RUN git clone https://github.com/rh-ecosystem-edge/kernel-module-management.git
              WORKDIR /build/kernel-module-management/ci/kmm-kmod
              RUN make


              FROM registry.redhat.io/ubi8/ubi-minimal
              ARG KERNEL_VERSION
              RUN microdnf -y install kmod
              COPY --from=builder /usr/bin/kmod /usr/bin/
              RUN for link in /usr/bin/modprobe /usr/bin/rmmod; do \
                  ln -s /usr/bin/kmod "$link"; done

              COPY --from=builder /build/kernel-module-management/ci/kmm-kmod/*.ko /opt/lib/modules/${KERNEL_VERSION}/
              RUN depmod -b /opt
      
  selector:
    feature.kmm.lab: 'true'

