---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm-ci-a
      kernelMappings:
        - literal: 4.18.0-372.19.1.el8_6.x86_64
          containerImage: image-registry.openshift-image-registry.svc:5000/default/kmm-kmod:4.18.0single
          build:
            dockerfileConfigMap:
              name: build-module-single
  selector:
    feature.kmm.lab: 'true'
