---
apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci-a
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm-ci-a
      kernelMappings:
        - literal: 4.18.0-372.19.1.el8_6.x86_64 
          containerImage: image-registry.openshift-image-registry.svc:5000/default/kmm-kmod:4.18.0single
          pull:
            insecureSkipTLSVerify: true
          build:
            pull:
              insecureSkipTLSVerify: true
            push:
              insecureSkipTLSVerify: true
            dockerfile: |
              FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:82faeb6a8caa174d9df3d259945ca161311fe6231d628e34ee0f1c8528371229 AS builder
              ARG KERNEL_VERSION
              WORKDIR /build
              RUN git clone https://github.com/rh-ecosystem-edge/kernel-module-management.git 
              WORKDIR /build/kernel-module-management/ci/kmm-kmod
              RUN make 

              RUN mkdir -p /opt/lib/modules/${KERNEL_VERSION} && \
                  cp /build/kmm-kmod/*.ko /opt/lib/modules/${KERNEL_VERSION}/

              RUN depmod -b /opt
      
  selector:
    feature.kmm.lab: 'true'
