---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm_ci_a
      kernelMappings:
        - literal: KVER_CHANGEME
          containerImage: image-registry.openshift-image-registry.svc:5000/default/kmm-kmod:local
          registryTLS:
            insecure: true
          build:
            buildArgs:
              - name: CI_BUILD_ARG
                value: some-build-arg
            secrets:
              - name: build-secret
            dockerfileConfigMap:
              name: kmm-kmod-dockerfile
  selector:
    task: kmm-ci
