---
apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: kmm-ci
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: kmm_ci_a
      imagePullPolicy: Never
      kernelMappings:
        - regexp: '^.+$'
          containerImage: image-registry.openshift-image-registry.svc:5000/default/kmm-kmod:$KERNEL_FULL_VERSION
  selector:
    task: kmm-ci
