site_name: Out-Of-Tree operator
repo_url: https://github.com/kubernetes-sigs/kernel-module-management
edit_uri: edit/main/docs/

docs_dir: mkdocs
strict: true

plugins:
  - exclude:
      glob:
        - developer/diagrams/*.puml
        - developer/Makefile
