---
site_name: Kernel Module Management
repo_url: https://github.com/rh-ecosystem-edge/kernel-module-management
edit_uri: edit/main/docs/mkdocs
site_description: Kernel Module Management (KMM) is a operator that manages, builds, signs and deploys out-of-tree kernel modules and device plugins on OpenShift clusters.
site_url: https://openshift-kmm.netlify.app/

docs_dir: mkdocs
strict: true

nav:
  - index.md
  - Documentation:
      - documentation/install.md
      - documentation/configure.md
      - documentation/deploy_kmod.md
      - documentation/kmod_image.md
      - Binary firmwares: documentation/firmwares.md
      - Secure boot: documentation/secure_boot.md
      - Preflight validation: documentation/preflight_validation.md
      - Ordered upgrade: documentation/ordered_upgrade.md
      - documentation/hub_spoke.md
      - Day1 support: documentation/day1_limited_option.md
      - Managing day-0/day-1 kmods: documentation/day0_day1_handover.md
      - documentation/troubleshooting.md
      - documentation/uninstall.md
  - Labs:
      - lab.md
      - labsv2.md 
  - Developer:
      - developer/index.md
      - developer/use_cases.md
      - developer/reconciliation_loops.md

plugins:
  - exclude:
      glob:
        - developer/diagrams/*.puml
        - developer/Makefile

markdown_extensions:
  - admonition

theme:
  name: readthedocs
  custom_dir: overrides/
  highlightjs: true
  hljs_languages:
    - dockerfile
    - shell
    - yaml
