name: GitStream

concurrency: gitstream

on:
  issues:
    types: [closed]

  pull_request:
    types: [closed]

  schedule:
    - cron: '*/10 * * * *'

jobs:
  gitstream:
    name: Run GitStream
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/qbarrand/gitstream:main

    steps:
      - name: Install Git
        run: apk add git

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout the downstream repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          path: _gitstream_downstream

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Bring upstream commits
        run: gitstream sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make the oldest draft PR ready for review
        run: gitstream make-oldest-draft-pr-ready
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
