name: GitStream

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  gitstream:
    name: Install and run GitStream
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install GitStream
        run: go install github.com/qbarrand/gitstream@latest

      - name: Run GitStream
        run: |
          ${HOME}/go/bin/gitstream \
            sync \
            --dry-run \
            --upstream-url https://github.com/qbarrand/test-upstream \
            --downstream-since 2022-01-01 \
            --downstream-repo-name ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
